

FUNC_KW = 'func'
LINE_NO_KW = 'lineno'
KEY_WORDS_KW = 'keywords'
INDEX_KW = '_index_'
ARGS_KW = 'args'
ATTRIB_KW = 'attr'
VALUE_KW = 'value'
NAME_KW = 'name'
NAMES_KW = 'names' 
BODY_KW = 'body'
BASE_KW = 'bases'
ELT_KW = 'elt'
GENERATORS_KW = 'generators'
EMPTY_STRING = ""
TARGETS_KW = 'targets'
LINE_NO_KW = 'lineno'
FUNC_CALL_ARG_STR = 'FUNC_CALL_ARG:'


TENSOR_LIB = 'tensorflow'

KERAS_LIB = 'keras'
SEQUENTIAL_KW = 'Sequential'
LAYERS_KW = 'layer'
DENSE = 'Dense'
CONV1D = 'Conv1D'
CONV2D = 'Conv2D'
CONV3D = 'Conv3D'
SEPARABLE_CONV1D = 'SeparableConv1D'
SEPARABLE_CONV2D = 'SeparableConv2D'
DEPTH_CONV2D = 'DepthwiseConv2D'
CONV2D_TRANSPOSE = 'Conv2DTranspose'
CONV3D_TRANSPOSE = 'Conv3DTranspose'
MAX_POOL_1D = 'MaxPooling1D'
MAX_POOL_2D = 'MaxPooling2D'
MAX_POOL_3D = 'MaxPooling3D'
AVRG_POOL_1D = 'AveragePooling1D'
AVRG_POOL_2D = 'AveragePooling2D'
AVRG_POOL_3D = 'AveragePooling3D'
AVG_POOL_1D = 'AvgPool1d'
AVG_POOL_2D = 'AvgPool2d'
AVG_POOL_3D = 'AvgPool3d'
GLOBAL_MAX_POOL_1D = 'GlobalMaxPooling1D'
GLOBAL_MAX_POOL_2D = 'GlobalMaxPooling2D'
GLOBAL_MAX_POOL_3D = 'GlobalMaxPooling3D'
GLOBAL_AVG_POOL_1D = 'GlobalAveragePooling1D'
GLOBAL_AVG_POOL_2D = 'GlobalAveragePooling2D'
GLOBAL_AVG_POOL_3D = 'GlobalAveragePooling3D'
LSTM = 'LSTM'
GRU = 'GRU'
SIMPLE_RNN = 'SimpleRNN'
BIDIRECTIONAL = 'Bidirectional'
TIME_DISTRIBUTED = 'TimeDistributed'
CONV_LSTM = 'ConvLSTM2D'
RNN = 'RNN'

TORCH_LIB = 'torch'

SKLEARN_LIB = 'sklearn'
RIDGE_CLASSIFIER = 'RidgeClassifier'
RIDGE_CLASSIFIER_CV = 'RidgeClassifierCV'
SVC = 'SVC'
NU_SVC = 'NuSVC'
LINEAR_SVC = 'LinearSVC'
SVR = 'SVR'
SGD_CLASSIFIER= 'SGDClassifier'
NEAREST_NEIGHBOUR = 'NearestNeighbors'
K_NEIGHBOUR = 'KNeighborsClassifier'
KD_TREE = 'KDTree'
NEAREST_CENTROID = 'NearestCentroid'
GAUSSIAN_PROCESS = 'GaussianProcessClassifier'
GAUSSIAN_NB = 'GaussianNB'
MULTINOMIAL_NB = 'MultinomialNB'
COMPLEMENT_NB = 'ComplementNB'
BERNOULI_NB = 'BernoulliNB'
CATEGORICAL_NB = 'CategoricalNB'
DECISION_TREE = 'DecisionTreeClassifier'
BAGGING = 'BaggingClassifier'
RANDOM_FOREST = 'RandomForestClassifier'
ADA_BOOST = 'AdaBoostClassifier'
GRADIENT_BOSTING = 'GradientBoostingClassifier'
HIST_GRADIENT_BOSTING= 'HistGradientBoostingClassifier'
VOTING = 'VotingClassifier'
STACKING = 'StackingClassifier'
EXTRA_TREE = 'ExtraTreesClassifier'
MLP = 'MLPClassifier'

all_possible_algo = [DENSE, CONV1D, CONV2D, CONV3D, SEPARABLE_CONV1D, SEPARABLE_CONV2D, DEPTH_CONV2D, CONV2D_TRANSPOSE, CONV3D_TRANSPOSE, \
                     MAX_POOL_1D, MAX_POOL_2D, MAX_POOL_3D, AVRG_POOL_1D, AVRG_POOL_2D, AVRG_POOL_3D, AVG_POOL_1D, AVG_POOL_2D, AVG_POOL_3D, GLOBAL_MAX_POOL_1D, GLOBAL_MAX_POOL_2D, \
                     GLOBAL_MAX_POOL_3D, GLOBAL_AVG_POOL_1D, GLOBAL_AVG_POOL_2D, GLOBAL_AVG_POOL_3D, LSTM, GRU, SIMPLE_RNN, BIDIRECTIONAL, \
                     TIME_DISTRIBUTED, CONV_LSTM, RNN, RIDGE_CLASSIFIER, RIDGE_CLASSIFIER_CV, SVC, NU_SVC, LINEAR_SVC, SVR, SGD_CLASSIFIER, \
                     NEAREST_NEIGHBOUR, K_NEIGHBOUR, KD_TREE, NEAREST_CENTROID, GAUSSIAN_PROCESS, GAUSSIAN_NB, MULTINOMIAL_NB, COMPLEMENT_NB, \
                     BERNOULI_NB, CATEGORICAL_NB, DECISION_TREE, BAGGING, RANDOM_FOREST, ADA_BOOST, GRADIENT_BOSTING, HIST_GRADIENT_BOSTING, \
                     VOTING, STACKING, EXTRA_TREE, MLP]


KERAS_ACCURACY = 'Accuracy'
KERAS_BINARY_ACCURACY = 'BinaryAccuracy'
KERAS_CATEGORICAL_ACCURACY = 'CategoricalAccuracy'
KERAS_SPARSE_CATEGORICAL_ACCURACY = 'SparseCategoricalAccuracy'
KERAS_TOPK_CATEGORICAL_ACCURACY = 'TopKCategoricalAccuracy'
KERAS_SPARSE_TOPK_CATEGORICAL_ACCURACY = 'SparseTopKCategoricalAccuracy'
KERAS_AUC = 'AUC'
KERAS_PRECISION = 'Precision'
KERAS_RECALL = 'Recall'
KERAS_TP = 'TruePositives'
KERAS_TN = 'TrueNegatives'
KERAS_FP = 'FalsePositives'
KERAS_FN = 'FalseNegatives'
KERAS_PRECISION_RECALL = 'PrecisionAtRecall'

SKLEARN_ACCURACY_METRIC = 'accuracy_score'
SKLEARN_F1_METRIC = 'f1_score'
SKLEARN_PRECISION_METRIC = 'precision_score'
SKLEARN_RECALL_METRIC = 'recall_score'
SKLEARN_AUC_METRIC = 'roc_auc_score'
SKLEARN_ALL_METRIC = 'precision_recall_fscore_support'

all_possible_metric = [KERAS_ACCURACY, KERAS_BINARY_ACCURACY, KERAS_CATEGORICAL_ACCURACY, KERAS_SPARSE_CATEGORICAL_ACCURACY, \
                       KERAS_TOPK_CATEGORICAL_ACCURACY, KERAS_SPARSE_TOPK_CATEGORICAL_ACCURACY, KERAS_AUC, KERAS_PRECISION, KERAS_RECALL, \
                       KERAS_TP, KERAS_TN, KERAS_FP, KERAS_FN, KERAS_PRECISION_RECALL, SKLEARN_ACCURACY_METRIC, SKLEARN_F1_METRIC, \
                       SKLEARN_PRECISION_METRIC, SKLEARN_RECALL_METRIC, SKLEARN_AUC_METRIC, SKLEARN_ALL_METRIC]


TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
UTF_ENCODING   = 'utf-8'

