name: Fuzzing Workflow
on: [workflow_dispatch]
jobs:
  example:
    name: Fuzz Methods
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.2.0
      - run: python fuzzing.py
        shell: bash
